#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

ARGS=("${@}")
MC_DATA_DIR="${DATA_DIR:-$PWD/data/wahooMapsCreatorData}"

mkdir -p "${MC_DATA_DIR}"

xhost +"local:podman@"

docker run --rm -it \
	--pull always \
	-e DISPLAY \
	--security-opt=label=type:container_runtime_t \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v "${MC_DATA_DIR}:/root/wahooMapsCreatorData:Z" \
	-v "${PWD}:/app:Z" \
	ghcr.io/zoenglinghou/wahoo-maps-creator:master \
	"gui" "${ARGS[@]}"
